apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  type: NodePort
  selector:
    app: posts
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: posts 
      protocol: TCP
      port: 4000
      targetPort: 4000